# Generated by Django 5.0.1 on 2024-03-20 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eduprod', '0002_question_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='category',
        ),
    ]
